version: '3.8'

services:
  web:
    image: itzg/rcon
    environment:
      RWA_USERNAME: admin
      RWA_PASSWORD: 4dm1n
      RWA_ADMIN: "TRUE"
      RWA_RCON_PORT: 27015
      # is referring to the hostname of 'l4d2'
      RWA_RCON_HOST: l4d2
      RWA_RCON_PASSWORD: annikkikyllikki

    ports:
      - 4326:4326
      - 4327:4327
  l4d2:
    image: left4devops/l4d2
    restart: always
    environment:
      SV_HOSTNAME: "[DLR] My server"
      SV_RCON_PASSWORD: "annikkikyllikki"
    ports:
      - 27015:27015
    volumes:
       -  ${PWD}/l4d2/cfg/server.cfg:/home/louis/l4d2/left4dead2/cfg/server.cfg
       -  ${PWD}/l4d2/cfg/autoexec.cfg:/home/louis/l4d2/left4dead2/cfg/autoexec.cfg
       - './l4d2/addons:/home/louis/l4d2/left4dead2/addons'
       - './l4d2/cfg/sourcemod:/home/louis/l4d2/left4dead2/cfg/sourcemod'
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mysql
    volumes:
      - ./mysqldata:/var/lib/mysql
    networks:
      - internal
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8000   
  nginx:
    image: nginx:alpine
    ports:  
      - "8080:8080"
    volumes:
            - './php-files:/var/www/html'
            - './nginx-conf:/etc/nginx/conf.d'
  # Volumes
volumes:
  mysqldata:
  php-files:
  nginx-conf:

networks:
  internal:
    driver: bridge


