version: '3.8'

services:
  web:
    image: itzg/rcon
    environment:
      RWA_USERNAME: admin
      RWA_PASSWORD: 4dm1n
      RWA_ADMIN: "TRUE"
      RWA_RCON_PORT: 27015
      # is referring to the hostname of 'l4d2'
      RWA_RCON_HOST: l4d2
      RWA_RCON_PASSWORD: annikkikyllikki

    ports:
      - 4326:4326
      - 4327:4327
  l4d2:
    image: left4devops/l4d2
    restart: always
    environment:
      HOSTNAME: "[DLR] Test Server"
      RCON_PASSWORD: "annikkikyllikki"
      MAP: "c2m1_highway"
    ports:
      - 27015:27015/tcp
      - 27015:27015/udp
    volumes:
       -  ${PWD}/l4d2/cfg/server.cfg:/home/louis/l4d2/left4dead2/cfg/server.cfg
       -  ${PWD}/l4d2/motd.txt:/home/louis/l4d2/left4dead2/motd.txt
       -  ${PWD}/l4d2/host.txt:/home/louis/l4d2/left4dead2/host.txt
       -  ${PWD}/l4d2/cfg/autoexec.cfg:/home/louis/l4d2/left4dead2/cfg/autoexec.cfg
       -  ${PWD}/l4d2/libz.so.1:/usr/lib/libz.so.1
       - './l4d2/addons:/home/louis/l4d2/left4dead2/addons:rw'
       - './l4d2/cfg/sourcemod:/home/louis/l4d2/left4dead2/cfg/sourcemod:rw'
  l4d2_2:
    image: left4devops/l4d2
    restart: always
    environment:
      HOSTNAME: "[DLR] Docker template"
      RCON_PASSWORD: "annikkikyllikki"
      MAP: "l4d2_timemachine_01"
      PORT: 27016
    ports:
      - 27016:27016/tcp
      - 27016:27016/udp
    volumes:
       -  ${PWD}/l4d2_2/cfg/server.cfg:/home/louis/l4d2/left4dead2/cfg/server.cfg
       -  ${PWD}/l4d2/motd.txt:/home/louis/l4d2/left4dead2/motd.txt
       -  ${PWD}/l4d2/host.txt:/home/louis/l4d2/left4dead2/host.txt
       -  ${PWD}/l4d2_2/cfg/autoexec.cfg:/home/louis/l4d2/left4dead2/cfg/autoexec.cfg
       -  ${PWD}/l4d2/libz.so.1:/usr/lib/libz.so.1
       - './l4d2/addons:/home/louis/l4d2/left4dead2/addons:rw'
       - './l4d2/cfg/sourcemod:/home/louis/l4d2/left4dead2/cfg/sourcemod:rw'

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mysql
    volumes:
      - ./mysqldata:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8000   
  nginx:
    image: nginx:alpine
    ports:  
      - "8080:8080"
    volumes:
            - './php-files:/var/www/html'
            - './nginx-conf:/etc/nginx/conf.d'
  # Volumes
volumes:
  mysqldata:
  php-files:
  nginx-conf:

networks:
  internal:
    driver: bridge


